apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-1
  labels:
  app: node  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: node
        command: ["sleep","3600"]
        ports:
        - containerPort: 80
