apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels: 
    env: frontend
spec:
  containers: 
    - name: pod-1
      image: busybox:latest
      command: ['sh','-c']
      args: ['echo 'this is main container' && sleep 3600']

  initContainers:
    - name: init-myservice
      image: busybox:latest
      command: ['sh','-c']
      args: ['until nslookup myservice.default.svc.cluster.local; do echo this is init container;sleep 2;done']
    - name: init-mydb
      image: busybox:latest
      command: ['sh','-c']
      args: ['until nslookup mydb.default.svc.cluster.local; do echo this is init container;sleep 2;done']
      
