apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  namespace: frontend
  labels: 
        env: frontend
spec:
  initontainers:
    - name: init-pod
      image: nginx
      command: ["sh","-c"]
      args: ["echo 'this is init container';sleep 20"]
      
  containers: 
    - name: pod-1
      image: nginx
      command: ["sh","-c"]
      args: ["echo 'this is main container';sleep 20"]
