apiVersion: v1
kind: Service
metadata:
  name: service-np
  namespace: frontend
  labels:
    env: ui
spec: 
  type: NodePort
  selector:
    env: ui
  ports: 
  - port: 80
    nodePort: 31111
    targetPort: 80


---
apiVersion: v1
kind: Service
metadata:
  generateName: service-
  namespace: frontend
  labels:
    env: ui
spec: 
  type: LoadBalancer
  selector:
    env: ui
  ports:
  - port: 80
    targetPort: 80



  
