apiVersion: v1
kind: Service
metadata:
  name: Service
  namespace: frontend
  lables:
    env: ui
    generateName: service-
spec: 
  type: NodePort
  - nodeport: 31111
    port:80
    target: 80
  selector:
    matchLabels:
      env: ui

---
apiVersion: v1
kind: Service
metadata:
  name: Service
  namespace: frontend
  lables:
    env: ui
    generateName: service-
spec: 
  type: LoadBalancer 
  - port: 80
    target: 80
  selector:
    matchLabels:
      env: ui

---

apiVersion: v1
kind: Service
nodes: 
- role: control-plane
  exterPortMappings: 
  - containerPort: 31111
    hostPort: 31111
- role: worker
- role: worker
  
